name: Erin Schrad Creative
favicon: null
layout_spectrum: 0.02568710781633854
typography_spectrum: 0.3659999400842935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.773537723813206
  saturation: 0.9406531450804323
  rhythmicContrast: 0.5908879430498928
purpose: []
